### ISSUE TITLE
Merge to gh-pages  fails on "Update Suttas and CI/Merge " action

### ISSUE THREAD

**Issue by bkhpanigha** [bkhpanigha/hh-suttas#49]
![image](https://github.com/bkhpanigha/hh-suttas/assets/53958588/a5e185af-cbbe-4f4b-a07b-f2480f5776a3)

Only works when merging manually on local machine.

**Comment by bkhpanigha** [comment]
![image](https://github.com/bkhpanigha/hh-suttas/assets/53958588/873a0a46-b2ee-4d0e-8b61-4cfacbb8daef)
@ishaanv all checks passed for PR #50, but got the same error for the files that were being modified in PR #46, as seen above.

**Comment by ishaanv** [comment]
Ok it seems somehow that `gh-pages` has diverged from main. It could be that some changes were commit directly to `gh-pages` instead of going through main via CI. E.g. this commit d0e8b65 seems to be on gh-pages but not in main. What you could do as a one time thing is force push main onto `gh-pages` with the -f flag.

```while latest main is checked out: git push -f origin gh-pages```

This way `gh-pages` should completely reflect main. Then going forward we will only push changes to main.

**Comment by bkhpanigha** [comment]
@ishaanv It seems one reason why the merges work locally but not GH actions is that locally git merges with the 'ort' strategy, which apparently is not available when merging through GH, which uses the 'recursive' strategy. `gh-pages` has diverged from main by 8 commits ATM because every time there is a merge it creates a commit that won't be on the main branch, e.g. [`d0e8b65`](https://github.com/bkhpanigha/hh-suttas/commit/d0e8b651a5929f3f125e4a1fc176604d46cbacc1)  you linked. 

Whenever it fails, however, the apparent conflict is always regarding the latest commit in main, e.g. index.css and index.js, [`95307c0`](https://github.com/bkhpanigha/hh-suttas/commit/95307c03671ae5b8bee8094a374a3b5b28cddb58) in the second screenshot.

**Comment by ishaanv** [comment]
It might have been my config changes that could have caused it, which is why the same commit messages kept showing up in my PRs despite being merged. I think if you do a force push or delete `gh-pages` and create it again from main, it should solve the problem.

**Comment by bkhpanigha** [comment]
Issue is still ongoing for some reason, even though I've deleted and created ` gh-pages ` multiple times already. `git push -f origin gh-pages` doesn't seem to help either.

**Comment by ishaanv** [comment]
Yes I'm experiencing similar issues by trying the same scripts on my repo. One solution is to simply put the -f flag in the integration script. But let me investigate further for a more graceful solution and get back to you.
